site_author: Ryan Morshead
site_description: A modern dependency injection framework for Python.
site_name: PyBooster
docs_dir: src

repo_url: https://github.com/rmorshea/pybooster

nav:
    - Home: index.md
    - Tutorials: tutorials.md
    - Concepts: concepts.md
    - Examples: examples.md
    - Reference: reference.md

theme:
    name: material
    icon:
        repo: fontawesome/brands/git-alt
        logo: material/needle
    features:
        - content.code.copy

plugins:
    - search
    - open-in-new-tab
    - mkdocstrings:
          handlers:
              python:
                  options:
                      docstring_style: google
                      members_order: alphabetical
                      merge_init_into_class: true
                      separate_signature: true
                      show_labels: false
                      show_object_full_path: true
                      show_root_heading: true
                      show_signature_annotations: true
                      show_source: true
                      show_submodules: true
                      show_symbol_type_heading: true
                      show_symbol_type_toc: true
                      signature_crossrefs: true

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
