---
site_author: Ryan Morshead
site_description: A modern dependency injection framework for Python.
site_name: PyBooster
docs_dir: src
repo_url: https://github.com/rmorshea/pybooster
nav:
  - Home: index.md
  - Concepts: concepts.md
  - Recipes: recipes.md
  - Integrations: integrations.md
  - Examples: examples.md
  - Reference: reference.md
  - Contributing: contributing.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
    logo: material/needle
  features: [content.code.copy, toc.integrate]
  palette:
    # Palette toggle for automatic mode
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
        # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  - open-in-new-tab
  - mkdocstrings:
      handlers:
        python:
          import: [https://docs.sqlalchemy.org/en/latest/objects.inv]
          options:
            load_external_modules: true
            docstring_style: google
            members_order: alphabetical
            merge_init_into_class: true
            separate_signature: true
            show_labels: false
            show_object_full_path: true
            show_root_heading: true
            show_source: true
            show_submodules: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
